DATASETS:
  TEST: ("weinman_test","rumsey_test",)
  TRAIN: ("synmap_skeleton_ms_train", "synmap_osm_ms_train", "synmap_skeleton_train",
    "synmap_osm_train", "synthtext22_poly_train", "synthtext12_poly_train",)
MODEL:
  RESNETS:
    DEPTH: 50
  TRANSFORMER:
    DEC_LAYERS: 6
    DEC_N_POINTS: 4
    DIM_FEEDFORWARD: 1024
    DROPOUT: 0.1
    ENC_LAYERS: 6
    ENC_N_POINTS: 4
    HIDDEN_DIM: 256
    INFERENCE_TH_TEST: 0.3
    NHEADS: 8
    NUM_FEATURE_LEVELS: 4
    NUM_QUERIES: 100
  WEIGHTS: /ta1/inputs/modules/text_spotting/trained_weights/model_final.pth
OUTPUT_DIR: ''
SOLVER:
  BASE_LR: 1e-4
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 3
  LR_BACKBONE: 1e-5
  MAX_ITER: 480000
  STEPS: (360000,)
  WARMUP_ITERS: 0
TEST:
  EVAL_PERIOD: 5000
_BASE_: Base-SynthMap-Polygon.yaml
